[IV-21-22] Objetivo 3
argelion14/Sport-car pull request #16
Opened 2021-11-12 12:52 UTC by argelion14

2021-11-21 12:14 UTC, JJ requested changes
Los cambios tampoco están asociados a un issue, ni ese issue (y este PR) a un hito.

2021-11-21 12:14 UTC, JJ commented on docs/gestores.md
> +# Instalación
No hay ninguna justificación del que has elegido y por qué.

2021-12-02 08:44 UTC, argelion14 commented
Listo para revisión @JJ

2021-12-03 08:39 UTC, JJ requested changes
Tampoco es buena práctica que el cuerpo del PR esté vacío. Ya que hemos puesto la lista de comprobación, cópiala y síguela para la siguiente iteración.

2021-12-03 08:39 UTC, JJ commented on docs/gestores.md
> +He decidido usar poetry pues fue el primer gestor del que oí hablar, busqué información sobre este y vi lo sencillo que era sobre Invoke y la documentación que aportaba en su web me ayudo a entender
No se pide que comuniquéis una decisión, sino que establezcáis los parámetros para tomarla y la justifiquéis.

2021-12-03 12:19 UTC, argelion14 commented
Listo para revisión @JJ.

2021-12-07 16:34 UTC, JJ requested changes
Otra vuelta, por favor, sobre todo la justificación, pero también el hecho de que realmente hagas lo que se pide.

2021-12-07 16:34 UTC, JJ commented on README.md
> +## Comprobar la sintasis
:eyes: typo

2021-12-07 16:34 UTC, JJ commented on docs/gestores.md
> +He decidido usar poetry pues fue el primer gestor del que oí hablar, busqué información sobre este y vi lo sencillo que era sobre Invoke y la documentación que aportaba en su web me ayudo a entender
¿has leído la lista de comprobación? Tendrás que justificar poetry un poco más, sobre todo con criterios que sean previos a la elección y que muestre que has mirado las diferentes opciones que hay.

2021-12-07 16:34 UTC, JJ commented on docs/gestores.md
> +# Uso
Esto no hace falta, está copiado y no tiene nada que ver con tu proyecto.

2021-12-07 16:34 UTC, JJ commented on pyproject.toml
> +[tool.poetry]
No tienes una orden check en el fichero. Y antes de que metas pylint, NO, no es necesario para comprobar la sintaxis.

2021-12-08 23:49 UTC, argelion14 commented on pyproject.toml
> +[tool.poetry]
La orden check como tal la tengo en el archivo readme.me la cual me sirve para comprobar que la estructura del fichero pyproject.toml es correcta, entiendo que por eso no hace falta el pylint.

2021-12-08 23:49 UTC, argelion14 commented
Listo para revisión @JJ

2021-12-09 19:08 UTC, JJ commented on pyproject.toml
> +[tool.poetry]
La tienes que tener en el gestor de tareas que hayas elegido.

2021-12-09 19:10 UTC, JJ requested changes
Por favor, repasa lo que realmente se pide en el target check, que no es lo que tú has puesto aquí (ni tiene mucho sentido)

2021-12-09 19:10 UTC, JJ commented on README.md
> +Con el siguiente comando comprobamos que la estructura del fichero pyproject.toml es correcta o devuelve un informe en caso de que haya algún error
OK, no es eso lo que se pide. Lo que tienes que comprobar es que las clases que ya estén en tu repositorio compilen.

2021-12-09 19:10 UTC, JJ commented on docs/gestores.md
> +Para comprobar que el archivo pyproject.toml es correcto ejecutamos
No se pide eso. Y lo que tienes que tener es un target `check` en el gestor de tareas.

2021-12-09 19:10 UTC, JJ commented on docs/gestores.md
> +#### En caso de tener pylint
Esto tampoco se pide, ni sirve para mucho ahora mismo.

2021-12-16 09:24 UTC, argelion14 commented
Listo para revisión @JJ a falta de quitar lo de poetry si quiere

2021-12-16 19:36 UTC, JJ requested changes
Por favor, dale una vuelta a los temas que se han comentado.

2021-12-16 19:36 UTC, JJ commented on docs/gestores.md
> +~~Usaremos pyflakes para la comprobación sintasis/compilación de los ficheros~~
Agh, no. Simplemente comprobar que compila. Also: sintaxis.

2021-12-16 19:36 UTC, JJ commented on docs/gestores.md
> +[Instalación: sudo apt-get install pylint](https://pylint.org/#install)
Agh, tampoco pylint, tres cuartos de lo mismo. Y *NUNCA* instales tus herramientas de desarrollo de los repos, igual que los lenguajes.

2021-12-16 19:36 UTC, JJ commented on docs/gestores.md
> +He decidido usar poetry pues fue el primer gestor del que oí hablar, busqué información sobre este y vi lo sencillo que era sobre Invoke y la documentación que aportaba en su web me ayudo a entender
No es una justificación muy técnica, ¿no te parece? Tampoco pedía que justificárais el gestor de dependencias.

2021-12-16 19:36 UTC, JJ commented on pyproject.toml
> +pytest = "^6.2.5"
¿Por qué tienes ya pytest?

2021-12-16 19:36 UTC, JJ commented on tasks.py
> +    #c.run("python setup.py build")
No dejéis nunca códigos comentados.

2021-12-17 12:06 UTC, argelion14 commented on docs/gestores.md
> +[Instalación: sudo apt-get install pylint](https://pylint.org/#install)
Nunca más, esto ya lo he entendido

2021-12-17 12:07 UTC, argelion14 commented on docs/gestores.md
> +He decidido usar poetry pues fue el primer gestor del que oí hablar, busqué información sobre este y vi lo sencillo que era sobre Invoke y la documentación que aportaba en su web me ayudo a entender
Esto lo he eliminado, para el objetivo 3 no se pido

2021-12-17 12:07 UTC, argelion14 commented on pyproject.toml
> +pytest = "^6.2.5"
Lo instalé con poetry pero ya no lo voy a usar, fuera

2021-12-17 12:09 UTC, argelion14 commented
Listo para revisión @JJ

2021-12-17 19:03 UTC, JJ requested changes
La justificación es muy importante, y esta es de las más simples. Por favor, dale la atención que merece.

2021-12-17 19:03 UTC, JJ commented on tasks.py
> +    print("Compilacion nice!")
Se escribe NAIS

2021-12-17 19:03 UTC, JJ commented on docs/gestores.md
> +[Instalar Invoke](https://www.pyinvoke.org/installing.html)
Vamos a ver. Mira que lo hemos dicho veces. Siempre tienes que hacer una justificación de la herramienta elegida dentro de todas las que haya disponibles, siguiendo un serie de criterios objetivos. Por favor, mira un poco el panorama y las mejores prácticas en Python el 2021 y actualiza esto.

2021-12-26 10:35 UTC, argelion14 commented on tasks.py
> +    print("Compilacion nice!")
mmm oki, lo cambio

2021-12-26 10:41 UTC, argelion14 commented on docs/gestores.md
> +[Instalar Invoke](https://www.pyinvoke.org/installing.html)
Puse una serie de características, por las que elegí invoke en el objetivo 3 pero es verdad no son las mejores, lo actualizo según las mejores prácticas. Gracias por la paciencia

2021-12-29 19:16 UTC, argelion14 commented
Listo para revisión @JJ. He continuado con el objetivo 4 pese a que no estaba este aceptado, pero como no puedo cambiar nada (en esta entrega fuera de clases) espero no suponga un problema.

2022-01-08 19:21 UTC, JJ requested changes
Siento haber tardado tanto, pero no pasa tampoco.

2022-01-08 19:21 UTC, JJ commented on docs/gestores.md
> +He decidido usar la herramienta externa invoke como gestor de tareas de python en mi proyecto, en un primer paso y a nivel objetivo por lo que ofrece, una API de alto nivel y clara que permite ejecut
No se trata de que comuniques una decisión, sino de que examines diferentes opciones siguiendo una metodología y te decantes por el que siga los criterios.

2022-01-08 19:21 UTC, JJ commented on docs/gestores.md
> +Se seguirá la documentación oficial para instalar invoke por lo que se usará el gestor de dependencias pip.
Tampoco se debe usar `pip` a estas alturas, lo hemos dicho repetidamente en clase.

2022-01-12 20:28 UTC, argelion14 commented on docs/gestores.md
> +He decidido usar la herramienta externa invoke como gestor de tareas de python en mi proyecto, en un primer paso y a nivel objetivo por lo que ofrece, una API de alto nivel y clara que permite ejecut
De acuerdo para la extraordinario, lo modifica gracias! 😄

2022-01-12 20:29 UTC, argelion14 commented on docs/gestores.md
> +Se seguirá la documentación oficial para instalar invoke por lo que se usará el gestor de dependencias pip.
Si , en objetivos siguiente lo cambio, lo modifico eso. 👍

2022-01-12 23:15 UTC, closed without merging