[IV-21-22] Objetivo 4
argelion14/Sport-car pull request #19
Opened 2021-12-03 12:43 UTC by argelion14

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y de
   *framework* de test?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

2021-12-27 17:28 UTC, JJ commented
⛹ Revisores → @Balrrach @amerigal @eantoniocalo18

2021-12-28 09:36 UTC, lentes4k requested changes
Para empezar, buen trabajo. Se ve que has tratado de seguir buenas prácticas a la hora de trabajar y documentar.
Quisiera darte un tirón de orejas por usar `invoke` en lugar de `poetry` ya que la comunidad ha ido virando hacía el uso de la segunda. Si bien es cierto que `invoke` aun sigue siendo ampliamente utilizado y existe buena documentación para ello.
Ahora, me preocupan más estas dos cositas:
1. El tratamiento de errores está realizado de forma correcta si bien es cierto que podrías incluir más manejo de errores por ejemplo para evitar cadenas vacias o cadenas extremadamente largas que den conflicto en un futuro. Cosa que te recomiendo que hagas.
2. La utilización de la biblioteca de aserciones por defecto me parece buena, pero deberías de haber explorado antes otras opciones al menos para ver sus puntos fuertes y débiles. Es cierto que para un proyecto pequeño vale, pero ¿si terminase escalando? se podría quedar corta. Te recomiendo que le eches un vistazo a alguna herramienta más y documentes sus puntos fuertes y débiles sobre la herramienta escogida.
Por lo demás no veo ningún error, así que enhorabuena capo :+1:

2021-12-28 11:06 UTC, eantoniocalo18 commented
Tengo un par de cosas que creo que podrías mejorar:
- En primer lugar, la justificación de los gestores me parece escasa, tendrías que haber definido una serie de requisitos y ver cuáles de las herramientas probadas los cumplen y cuáles no. Además creo que tendrías que haber comparados más herramientas y no probar solo las más "populares".
- Por otro lado, los test que has creado están bien, pero creo que sería recomendable que incluyeras algo más de la lógica de negocio o, al menos, una parte de ella. 
Para ello, una buena manera sería tratar de implementar un test en el que se apoye la HU1 #5 en el que compruebes que efectivamente el usuario indicado no posee ningún vehículo. Esto prevendrá de futuros errores puesto que si quieres asignarle un vehículo a un usuario que ya lo tenga asignado, este se sobrescribirá y además te permite iniciar la implementación de la lógica de negocio.
Es solo una idea y espero que te sirva :)
Por lo demás, me parece que está todo bien, buen trabajo! 👍

2021-12-28 13:53 UTC, Balrrach commented
Refuerzo lo dos puntos que ha destacado lentes @lentes4k y el primero que ha destacado @eantoniocalo18.

Con el segundo punto de @eantoniocalo18 no estoy de acuerdo del todo. Pienso que no se ha testeado la lógica de negocio porque no se ha implementado lógica de negocio. El problema realmente es que, a excepción de #10 las HU no codifican problemas luego su implementación no va a ser lógica de negocio. Por lo tanto yo implementaría algo de la lógica de negocio relacionada con #10.

2021-12-29 13:03 UTC, argelion14 commented
Voy a trabajar más en los aspectos de lógica de negocio ahora, he comprendido mejor los framework de test y estoy orgulloso de haber trabajado con otro biblioteca de aserciones como es assertpy (El cual he usado para testear las fechas). He realizado los cambios que se me han sugerido referentes a la elección del framework de test y también añadí nuevas comprobaciones.

Ahora paso a realizar los cambios de @Balrrach buscando desarrollar más la lógica y testeandola.

2021-12-29 18:43 UTC, argelion14 commented
Listo para una revisión @eantoniocalo18, @Balrrach, y @lentes4k.
* He añadido una librería de aserciones nueva (assertpy) y he documentado el porque de su uso
* He añadido los errores de longitud de cadena como me indicó @lentes4k 
* He probado otros framework de test como Robot framworlk o redwoodHQ aunque he seguido apostando por unittest y lo he justificado en referente a lo que necesito para mi aplicación
* He añadido y testeado parte de la lógica de negocio que hay detras de sportcar

2021-12-29 19:30 UTC, eantoniocalo18 reviewed
Por mi parte todo bien.
Te he dejado un par de recomendaciones que puedes seguir, pero aún así, el objetivo está listo por mi parte 👍

2021-12-29 19:30 UTC, eantoniocalo18 commented on README.md
> +## Comprobar que compila
¿No crees que queda mejor 'Comprobar sintaxis'? 
jajaja me suena un poco raro así.

2021-12-29 19:30 UTC, eantoniocalo18 commented on docs/test.md
> +Para las assert se ha decidido usar la bilioteca que viene por defecto con python además de assertpy la cual me permite unas opciones más que necesito para validar mi código y también con la que pued
En mi proyecto también usé assertpy y no sé en qué medida es bueno que combines los assert de Python con los de assertpy. 
Supongo que no hay ningún problema pero piensa que todos los assert de Python podrías haberlos escrito usando assertpy y así no mezclas ( es una opinión )

2021-12-29 19:42 UTC, argelion14 commented on docs/test.md
> +Para las assert se ha decidido usar la bilioteca que viene por defecto con python además de assertpy la cual me permite unas opciones más que necesito para validar mi código y también con la que pued
Como tal solo he usado la aserción de assert_that en una ocasión, debido a la comodidad que presenta para cierto código, los assert de python,, los uso para cuando uso mis propios errores, también opino que usar más bibliotecas como me menciona @lentes4k puede ser mejor a la hora de escalar pues incorporo, nuevas y diferentes funcionalidades, aunque en esta ocasión, la he usado, también para aprender a usar otra biblioteca de terceros y tener también una dependencia y poder aprender de ello. Gracias por tu comentario 👍

2021-12-29 19:47 UTC, argelion14 commented on README.md
> +## Comprobar que compila
Si tienes razón, eso lo cambio ahora, fue lo primero que pensé. Gracias

2021-12-29 20:03 UTC, argelion14 reviewed
Revisado nuevamente

2021-12-30 08:32 UTC, lentes4k approved these changes
Yo lo veo ya fino :ok_hand: Es verdad que como dice @eantoniocalo18 es raro usar dentro del mismo proyecto dos librerias para lo mismo. Pero me parece lógica tu justificación de por aprender a usarla. No si el profe tendrá algún comentario al respecto debido a que sea mala práctica o algo así.
Por lo demás lo dicho, currazo y a por los siguientes :sunglasses:

2021-12-30 18:58 UTC, JJ commented
> Yo lo veo ya fino ok_hand Es verdad que como dice @eantoniocalo18 es raro usar dentro del mismo proyecto dos librerias para lo mismo. Pero me parece lógica tu justificación de por aprender a usarla. No si el profe tendrá algún comentario al respecto debido a que sea mala práctica o algo así. Por lo demás lo dicho, currazo y a por los siguientes sunglasses

Cada nueva dependencia hay que pensársela bien, e introducir dos para exactamente lo mismo... No sé. Habrá que verlo.

2021-12-30 19:02 UTC, JJ commented on docs/test.md
> +Para las assert se ha decidido usar la bilioteca que viene por defecto con python además de assertpy la cual me permite unas opciones más que necesito para validar mi código y también con la que pued
Usar `assert` no añade ninguna dependencia, en realidad.

2021-12-31 17:57 UTC, argelion14 commented
Listo para revisión @JJ

2022-01-01 09:53 UTC, JJ requested changes
Lo siento, pero esto es algo que hemos explicado repetidamente en clase. No se dice "he decidido no sé qué". Se establecen una serie de criterios específicos del proyecto para elegir una biblioteca y a continuación se hace. Esto no sólo lo hemos repetido en clase y es igual para todos los objetivos, sino que te lo han indicado los tres revisores @eantoniocalo18 @lentes4k y @Balrrach que han hecho un excelente trabajo. Este objetivo no está superado, tendrás que pasar al siguiente.

2022-01-02 02:36 UTC, argelion14 commented
> 

No entiendo esta parte, pues como me mencionaron mis compañeros en la revisión, busqué criterios para el uso de assertpy.

Creo que no quedó claro en mi forma de expresarme, pero entiendo el concepto de buscar criterios y lo reflejé en la documentación.

Estos criterios eran: 
* Una alta media de descargas semanales, que en este caso es de 35.340.
* Una comunidad activa que que me proporcione respuesta rápida y ágil antes posibles issues en la realización del proyecto.
* Una valoración positiva en github (329 estrellas)
* Una serie de assert que me ayuden a la hora de desarrollar el código (en este caso se encontró uno que beneficiaba particularmente para las afirmaciones de fecha).

Como se observa en el enlace que incorporo en la documentación se comprueba que la librería cumple estos criterios y por ello decide usarse.

Le pido al final, que reconsidere su valoración, ha sido un objetivo que he trabajado mucho, y cuyo propósito he alcanzado a entender.

@JJ

2022-01-05 13:27 UTC, merged

2022-02-13 17:17 UTC, JJ commented
No deberías haberlo fusionado si no estaba aceptado. Eso es básico.