[IV-21-22] Objetivo 5
argelion14/Sport-car pull request #24
Opened 2022-01-07 12:06 UTC by argelion14

* [ ]  ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ]  ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests?
* [ ]  ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ]  ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ]  ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello?

2022-01-07 19:34 UTC, JJ commented
⛹ Revisores → @eantoniocalo18 @JAntonioVR @paula1999

2022-01-08 09:46 UTC, lentes4k requested changes
Muy buen curro. Veo que has usado buenas prácticas en la realización y eso siempre es de elogiar ya que es el buen camino por el que ir. Abajo te dejo una serie de comentarios que te van a ayudar a mejorar un poquito tu trabajo. 
Como cosa que quizás si deberías de emplearte un poco más está en la documentación de la elección del contenedor. Se me queda un poquito corta.

2022-01-08 09:46 UTC, lentes4k commented on docs/docker.md
> +
typo -> proyecto

2022-01-08 09:46 UTC, lentes4k commented on docs/gestores.md
> +
mismo typo -> proyecto (eso de leer documentación en inglés y escribir en español a veces se atranca... jajajaja)

2022-01-08 09:46 UTC, lentes4k commented on tasks.py
>      print("Se han instalado correctamente las dependencias")
te recomiendo hacer `poetry update && poetry install` ya que el comando install por defecto lanzará las dependecias del `.lock` y muchas veces están anticuadas y dan problemas o bien has metido algo nuevo en el `pyproject.toml` y al no estar en el `.lock` se lo pasa por donde ya sabemos...


Además con el `update` actualizas en `.lock` que nunca está de mal

2022-01-08 09:46 UTC, lentes4k commented on tasks.py
> +    run("docker build . --file Dockerfile --tag argelio14/sport-car && docker run -t -v `pwd`:/app/test argelion14/sport-car")
typo -> argelion14 (despés de --tag)

2022-01-08 09:46 UTC, lentes4k commented on .github/workflows/docker-image.yml
no estoy del todo seguro, pero creo que ya que vamos a lanzar el script cuando modifiques el Dockerfile no es necesario que indiques explícitamente las ramas.
Añadido a esto, te recomiendo que también lances cuando modifiques este mismo archivo y los de dependencias

2022-01-08 10:16 UTC, JAntonioVR requested changes
Buenos días Ángel, he mirado tu proyecto, documentación y tal y aunque lo tienes muy bien encaminado tengo algunas propuestas. Por aquí te dejo algunas más referentes al proyecto en general:

* Sobre los issues, están bien creados y lo que te voy a decir ya no tiene remedio, pero es buena práctica que cada commit que haces que avance el proyecto referencie a un issue, así cuando vayas a consultar el issue puedes ver fácilmente el progreso que has ido siguiendo (y los revisores también).
* La documentación toca todos los aspectos necesarios, pero es un poco superflua, habría que ahondar un poco más.
* De cara al objetivo 6, en el cual vas a tener que testear distintas versiones de python, recomiendo parametrizar la construcción del Docker. Es sencillo, hay una orden `ARG` para Dockerfile y un argumento `--build-arg` para `docker build` que lo hacen. Aún así, es sólo una recomendación hacerlo en este objetivo, si no es en este tendrás que hacerlo en el siguiente.

Por lo demás te dejo algunas cosillas ahí abajo. Espero haberte ayudado. Mucho ánimo!

2022-01-08 10:16 UTC, JAntonioVR commented on Dockerfile
> +RUN poetry config virtualenvs.create false; poetry install
El `poetry config virtualenvs.create false` yo sé por qué es necesario, pero debes documentarlo por escrito.

2022-01-08 10:16 UTC, JAntonioVR commented on docs/gestores.md
> -Se seguirá la documentación oficial para instalar invoke por lo que se usará el gestor de dependencias pip.
He visto que usas `poetry` y tienes `invoke` en la lista de dependencias. ¿Este párrafo es de alguna versión anterior?

2022-01-08 22:06 UTC, argelion14 commented on docs/docker.md
> +
Cierto gracias 😅

2022-01-08 22:10 UTC, argelion14 commented on tasks.py
>      print("Se han instalado correctamente las dependencias")
Gracias! Cambio realizado y entendido 👍

2022-01-08 22:11 UTC, argelion14 commented on tasks.py
> +    run("docker build . --file Dockerfile --tag argelio14/sport-car && docker run -t -v `pwd`:/app/test argelion14/sport-car")
Corregido!! 👍

2022-01-08 22:13 UTC, argelion14 commented on .github/workflows/docker-image.yml
Si claro, tiene sentido, tengo que lanzar la action cuando se modifiquen las dependencias del programa, muchas gracias y elimino lo de las ramas, pues como me has comentado no tiene sentido, que las indique. Gracias! 😄

2022-01-08 22:17 UTC, argelion14 commented on docs/docker.md
> +Por ello se consultaron las posibles variantes del contenedor **oficial** de Dockerhub (aquí)[https://hub.docker.com/_/python].
Si, que lo realizo desde visual code y no lo comprové luego cuando lo subí, gracias! 👍

2022-01-08 22:20 UTC, argelion14 commented on Dockerfile
> +COPY poetry.lock pyproject.toml tasks.py /app/test/
Correcto, lo modifico y lo cambio, otra vez Gracias! 😄

2022-01-08 22:21 UTC, argelion14 commented on Dockerfile
> +RUN poetry config virtualenvs.create false; poetry install
Okey, lo documento dentro del docker.md donde explico las elecciones, gracias!

2022-01-08 22:44 UTC, argelion14 commented
> Muy buen curro. Veo que has usado buenas prácticas en la realización y eso siempre es de elogiar ya que es el buen camino por el que ir. Abajo te dejo una serie de comentarios que te van a ayudar a mejorar un poquito tu trabajo. Como cosa que quizás si deberías de emplearte un poco más está en la documentación de la elección del contenedor. Se me queda un poquito corta.

La documentación pasará a continuación a mejorarla, con numerosas pruebas objetivas que certifiquen mi elección. Gracias! 😄

2022-01-08 22:45 UTC, argelion14 commented on docs/docker.md
> +* Que sea oficial para evitar posibles problemas.
Voy a realizar pruebas también con ellos y lo documentaré en mi proyecto. Gracias! 😃

2022-01-08 22:46 UTC, argelion14 commented on docs/docker.md
> +No se consideró alpine como primera opción debido a [información](https://pythonspeed.com/articles/alpine-docker-python/) que aportaba que era más lento usar este en un docker de python, por ello se
Si, estoy de acuerdo, tengo que hacer más pruebas (especificarlas) y documentarlas. Gracias! 😄

2022-01-08 22:52 UTC, argelion14 commented
> Buenos días Ángel, he mirado tu proyecto, documentación y tal y aunque lo tienes muy bien encaminado tengo algunas propuestas. Por aquí te dejo algunas más referentes al proyecto en general:
> 
> * Sobre los issues, están bien creados y lo que te voy a decir ya no tiene remedio, pero es buena práctica que cada commit que haces que avance el proyecto referencie a un issue, así cuando vayas a consultar el issue puedes ver fácilmente el progreso que has ido siguiendo (y los revisores también).
> * La documentación toca todos los aspectos necesarios, pero es un poco superflua, habría que ahondar un poco más. Te lo dejo abajo más en detalle a lo que me refiero.
> * De cara al objetivo 6, en el cual vas a tener que testear distintas versiones de python, recomiendo parametrizar la construcción del Docker. Es sencillo, hay una orden `ARG` para Dockerfile y un argumento `--build-arg` para `docker build` que lo hacen. Aún así, es sólo una recomendación hacerlo en este objetivo, si no es en este tendrás que hacerlo en el siguiente.
> 
> Por lo demás te dejo algunas cosillas ahí abajo. Espero haberte ayudado. Mucho ánimo!

Si voy a realizar lo comentado, me gusta la idea de los issues y quiero mejorar eso aunque sea ahora y he decidido crear un issue que mejore lo comentado por los revisores para que así, luego sea más legible y accesible por los mismos. 

En cuanto a la documentación, la mejora de esta estoy en ello.

El último punto lo analizaré ahora, pero lo dejo como posible punto, no como necesario, para no abordar temas que no comprenden este objetivo, muchas gracias por los comentarios! 😄 

[X] Creación de issues que luego se harán referencia dentro de commits.

[ ] Mejora de la documentación.

[ ] Posible vistazo a  parametrizar la construcción del Docker.

2022-01-09 01:35 UTC, argelion14 commented
Se han realizado todas las mejoras mencionadas y cerrado los issues que había creado para mejorar el objetivo. Por favor echadle un vistazo cuando podáis @eantoniocalo18 @JAntonioVR @paula1999 y @lentes4k. 😃

2022-01-09 09:56 UTC, lentes4k approved these changes
Yo realmente lo veo ya niquelado 👌 
Solo te dejo una curiosidad (que supongo que habrás leído al ver la documentación, pero en caso de que no lo hayas visto te lo dejo por aquí) y es que los sobrenombres del contenedor `slim` son los apodos con los que se conocen a las diferentes versiones de Debian.
Por mi parte nada que añadir, a por el siguiente!! 🚀

2022-01-09 11:41 UTC, eantoniocalo18 requested changes
Muy buen trabajo, la verdad que todo correcto.
Con las revisiones de mis compañeros y el comentario realizado en el pyproject.toml yo creo que el objetivo está aprobado.
Por otra parte el uso del token es solo por seguridad, no tienes que hacerlo sino quieres, es un 'good to have'.
Por lo demás, a por el siguiente 🚀

2022-01-09 11:41 UTC, eantoniocalo18 commented on .github/workflows/docker-image.yml
> +        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
Github Action permite logearte con un token de seguridad que es único y no tienes que introducir la contraseña.
Es solo para que sepas que se puede usar, te enlazo la documentación https://github.com/docker/build-push-action#git-context

2022-01-09 11:41 UTC, eantoniocalo18 commented on pyproject.toml
> +assertpy = "^1.1"
¿No crees que assertpy iría dentro de las dev-dependencies?

2022-01-09 11:44 UTC, JAntonioVR approved these changes
Por mi parte está correcto, te dejo aquí un detallico sin importancia que creo que no entendiste en mi revisión anterior.
Enhorabuena por el trabajo realizado y gracias por hacernos caso y por tu amabilidad. Buena suerte en la corrección!

2022-01-09 11:44 UTC, JAntonioVR commented on Dockerfile
> +COPY ./poetry.lock ./pyproject.toml ./tasks.py /app/test/
Me refería a hacer `poetry.lock pyproject.toml tasks.py ./`

2022-01-09 11:49 UTC, JAntonioVR reviewed
Un detallico

2022-01-09 11:49 UTC, JAntonioVR commented on docs/docker.md
> +| Imagen | Tiempo | Tamaño | Ejecución de test |
Bueno, si que te voy a sugerir que especifiques ese "Tiempo" de qué es.

2022-01-09 16:31 UTC, argelion14 commented
> Yo realmente lo veo ya niquelado 👌 Solo te dejo una curiosidad (que supongo que habrás leído al ver la documentación, pero en caso de que no lo hayas visto te lo dejo por aquí) y es que los sobrenombres del contenedor `slim` son los apodos con los que se conocen a las diferentes versiones de Debian. Por mi parte nada que añadir, a por el siguiente!! 🚀

Muchas gracias por, la revisión y por el buen compañerismo que has tenido a la hora de revisarme, de verdad agradezco te hayas pasado a echarme una mano 💪.

2022-01-09 16:37 UTC, argelion14 commented on pyproject.toml
> +assertpy = "^1.1"
Sí, entiendo que es mejor ponerlo ahí, lo cambio, Gracias! 😄

2022-01-09 16:45 UTC, argelion14 commented on Dockerfile
> +COPY ./poetry.lock ./pyproject.toml ./tasks.py /app/test/
Ah, vale si, lo entiendo, entiendo porque si no se pisaría, se pisa cuando se monte, tengo que usar otro directorio. Uso otro directorio para hacer las instalaciones. Muchas gracias 😄

2022-01-09 16:46 UTC, argelion14 commented on docs/docker.md
> +| Imagen | Tiempo | Tamaño | Ejecución de test |
Efectivamente, le voy a poner es tiempo de construcción de la imagen, Gracias! 😄

2022-01-09 16:48 UTC, argelion14 commented
> Por mi parte está correcto, te dejo aquí un detallico sin importancia que creo que no entendiste en mi revisión anterior. Enhorabuena por el trabajo realizado y gracias por hacernos caso y por tu amabilidad. Buena suerte en la corrección!

Muchas gracias por todo, es maravilloso tener compañeros así, te agradezco todo tu trabajo en mi, y me alegro mucho me hayas tocado como revisor. Esperemos salga bien 💪

2022-01-09 16:58 UTC, argelion14 commented on .github/workflows/docker-image.yml
> +        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
He revisado la documentación, y he decidido cambiar cosas a parte de los comentado, muchas gracias, por todo y por enlazarme la documentación, muy útil. 😄

2022-01-09 17:03 UTC, argelion14 commented
> Muy buen trabajo, la verdad que todo correcto. Con las revisiones de mis compañeros y el comentario realizado en el pyproject.toml yo creo que el objetivo está aprobado. Por otra parte el uso del token es solo por seguridad, no tienes que hacerlo sino quieres, es un 'good to have'. Por lo demás, a por el siguiente 🚀

Muchas gracias por los comentarios y las mejoras que has aportado a mi proyecto, se agradecen las palabras de ánimo mucho. Gracias por todo 💪

2022-01-09 17:16 UTC, argelion14 reviewed
👍

2022-01-09 17:20 UTC, argelion14 commented
He revisado mis archivos nuevamente en busca de fallos, pero me gustaría tener una última opinión antes de entregar el objetivo, por favor si alguno, con uno me vale, me puede indicar si estaría listo nuevamente para pasar el objetivo se lo agradecería. @eantoniocalo18 @JAntonioVR @paula1999 y @lentes4k. A todos muchas gracias! 💪

2022-01-09 17:31 UTC, eantoniocalo18 commented
> He revisado mis archivos nuevamente en busca de fallos, pero me gustaría tener una última opinión antes de entregar el objetivo, por favor si alguno, con uno me vale, me puede indicar si estaría listo nuevamente para pasar el objetivo se lo agradecería. @eantoniocalo18 @JAntonioVR @paula1999 y @lentes4k. A todos muchas gracias! 💪

Por mi parte todo ok 👍

2022-01-09 17:45 UTC, argelion14 commented
Listo para revisión @JJ.

2022-01-09 19:56 UTC, JAntonioVR commented
Por mi parte está listo también 👍🏽 Buen trabajo 😁

2022-01-10 19:10 UTC, JJ approved these changes
Aunque tienes algún errorcito, por lo menos has hecho lo que se pedía. Buen trabajo.

2022-01-10 19:10 UTC, JJ commented on Dockerfile
> +LABEL maintainer="argelion14"
"Tú diles argelion14. Ellos ya saben a quién te refieres"

> O igual pon un email o algo...

2022-01-10 19:10 UTC, JJ commented on Dockerfile
> +COPY poetry.lock pyproject.toml tasks.py ./
Estás usando el directorio de trabajo para copiar cosas, un directorio que se va a "pisar" con tu repo. Además, no los borras.

2022-01-10 19:10 UTC, JJ commented on docs/docker.md
> +* Contendor base lo más simple posible en que no haya cosas de más necesarias para nuestro proyecto.
typo

2022-01-10 19:10 UTC, JJ commented on docs/docker.md
> +| python:3.10-alpine | 6.821s | 297.94MB | 0.002s |
Son diferentes versiones de Python, pero al menos te has molestado en hacer las pruebas.

2022-01-10 20:11 UTC, merged