[IV-21-22] Objetivo 6
argelion14/Sport-car pull request #32
Opened 2022-01-11 01:25 UTC by argelion14

* [ ]  ¿Se han configurado varios sistemas de integración continua?
* [ ]  ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [X]  ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   del lenguaje con las que funciona correctamente nuestra aplicación?
* [ ]  ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?

2022-01-11 15:44 UTC, lentes4k requested changes
Menudo sprint final, la meta está cerca 🥇 . Te reviso rapidamente para a ver si llegas a tiempo.
En general bien trabajado. La github action la veo guay y se ve en la documentación que has trabajado varios CI.
A parte de las minucias que te he comentado por aquí te dejo una serie de cosas que creo que debes cambiar.

- Los tests de azure se están skippeando (es decir, no se están lanzando), mira a ver que puede ser
- La documentación está guay, quizás quitaría alguna imagen que no aporta demasiado.
- En ambos sistemas testeas lo mismo, prueba en uno a simplemente lanzar los tests que programaste en hitos anteriores

2022-01-11 15:44 UTC, lentes4k commented on docs/CI_docs.md
> +* [X] Especificar porque se testea cada versión
typo -> por que

2022-01-11 15:44 UTC, lentes4k commented on docs/CI_docs.md
> +A continuación se edita la configuración y ponemos nuestros parametros, pondremos nuestra imagen docker, como máquina donde se ejecutaran los test siendo esta, que testea la version *3.10-slim-bulley
typo -> probaba

2022-01-11 15:44 UTC, lentes4k commented on docs/CI_docs.md
> +Se ha decidido descartar Semaphore CI y Travis por su condición de ser herramientas de CI de pago que ofrecen un servicio gratuito, en especial Travis se trabajó, y aunque resulte ser fácil de usar s
typo -> terminó

2022-01-11 15:49 UTC, argelion14 commented on docs/CI_docs.md
> +Se ha decidido descartar Semaphore CI y Travis por su condición de ser herramientas de CI de pago que ofrecen un servicio gratuito, en especial Travis se trabajó, y aunque resulte ser fácil de usar s
✏️

2022-01-11 15:50 UTC, argelion14 commented on docs/CI_docs.md
> +A continuación se edita la configuración y ponemos nuestros parametros, pondremos nuestra imagen docker, como máquina donde se ejecutaran los test siendo esta, que testea la version *3.10-slim-bulley
✏️

2022-01-11 15:50 UTC, argelion14 commented on docs/CI_docs.md
> +* [X] Especificar porque se testea cada versión
✏️

2022-01-11 16:17 UTC, argelion14 commented
> Menudo sprint final, la meta está cerca 🥇 . Te reviso rapidamente para a ver si llegas a tiempo. En general bien trabajado. La github action la veo guay y se ve en la documentación que has trabajado varios CI. A parte de las minucias que te he comentado por aquí te dejo una serie de cosas que creo que debes cambiar.
> 
> * Los tests de azure se están skippeando (es decir, no se están lanzando), mira a ver que puede ser
> * La documentación está guay, quizás quitaría alguna imagen que no aporta demasiado.
> * En ambos sistemas testeas lo mismo, prueba en uno a simplemente lanzar los tests que programaste en hitos anteriores

He mejorado la documentación y eliminado las fotos que considero, no aportan nada, también he mejorado la configuración de Azure y ya si sale que se han realizado los checks cuando debe, es decir según los casos, se skipean cuando no se modifica lo necesario para que se lancen. 

Respecto a los CI he querido que realicen lo mismo, a modo también de comparación entre una estructura y otra y darme cuanta de cual sería más útil a un futuro, en este caso Github Action, esta mejor integrado, más sencillo y sobre todo mucho más rápido.

Gracias por los comentarios espero una segunda vuelta @lentes4k 😄

2022-01-11 16:31 UTC, lentes4k commented
> > Menudo sprint final, la meta está cerca 🥇 . Te reviso rapidamente para a ver si llegas a tiempo. En general bien trabajado. La github action la veo guay y se ve en la documentación que has trabajado varios CI. A parte de las minucias que te he comentado por aquí te dejo una serie de cosas que creo que debes cambiar.
> > 
> > * Los tests de azure se están skippeando (es decir, no se están lanzando), mira a ver que puede ser
> > * La documentación está guay, quizás quitaría alguna imagen que no aporta demasiado.
> > * En ambos sistemas testeas lo mismo, prueba en uno a simplemente lanzar los tests que programaste en hitos anteriores
> 
> He mejorado la documentación y eliminado las fotos que considero, no aportan nada, también he mejorado la configuración de Azure y ya si sale que se han realizado los checks cuando debe, es decir según los casos, se skipean cuando no se modifica lo necesario para que se lancen.
> 
> Respecto a los CI he querido que realicen lo mismo, a modo también de comparación entre una estructura y otra y darme cuanta de cual sería más útil a un futuro, en este caso Github Action, esta mejor integrado, más sencillo y sobre todo mucho más rápido.
> 
> Gracias por los comentarios espero una segunda vuelta @lentes4k 😄

Pues revisados tus cambios y argumentandome que Azure _skippea_ cuando no hay cambios en el fichero (cosa que no sabía, ya me puedo ir a la cama siendo más sabio hoy jeje) sumado a que tu justifiación de hacer el mismo test en ambos ficheros me parece correcta (y en los requisitos de JJ no aparece que ambos sistemas tengan que testear cosas diferentes por obligación) te doy mi 👍 👍 👍 👍 👍

2022-01-11 16:31 UTC, lentes4k approved these changes

2022-01-11 16:53 UTC, argelion14 commented
Listo para revisión @JJ

2022-01-12 13:11 UTC, JJ approved these changes
Aunque algunas justificaciones no son muy buenas, sólo por las pruebas que has hecho, que es lo que persigue este objetivo, te mereces pasar.

2022-01-12 13:11 UTC, JJ commented on docs/CI_docs.md
> +Nos centraremos en la versión 3.8 de python pues es esta la que se ha usado para desarrollar el proyecto de manera local.
Eso *nunca* es una buena justificación para nada. Precisamente la integración continua sirve para saber en qué versiones funciona tu proyecto.

2022-01-12 21:31 UTC, merged